export const GET_MOVIE_BY_ID = 'http://localhost:3001/movies/'
export const GET_MOVIE_KEYPHRASE = 'http://localhost:3001/movies/keyPhrases/'
export const MOVIE_HOME = 'http://localhost:3001/movies/'
export const MOVIE_POSTER_HOME = 'http://www.thetvdb.com'
export const OMDB_MOVIE_NAME='http://localhost:3001/movies/'
export const COVID_URL = 'https://api.covid19api.com/'